#version: "3.9"

services:
  db:
    image: postgres:15
    container_name: taskdb
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskdb_user -d taskdb"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  app:
    build: .
    env_file:
      - .env
    container_name: task-service
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: /app/start.sh

volumes:
  pgdata:
